Issue #94 - improve how groups name is imported
AdvancedThreatAnalytics/threat-analytics-search pull request #100
Opened 2021-09-08 14:59 UTC by Saidmurod1996

Fixes #94

2021-09-08 16:33 UTC, tim-kodirov commented
If I edit groups with "Edit manually" button, the groups are overridden properly. However, if I try to import a file, the groups are gone even if there are some:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/29039752/132548859-11dffa25-91b4-4cb8-bc98-d3ba781df22f.png">

2021-09-09 19:40 UTC, Saidmurod1996 commented
@tim-kodirov The bug you found was occurring because we don't allow group length to be less than 3, that is why it was acting weirdly. Now it's fixed, and should work in the following way. So recheck considering the case.

If a file has less than 3 groups you should: update the name of the groups are than defined, and disabled the other groups (without changing their names).
> So if the file only has 1 group, then you will rename Group 1, disable Group 2 and 3, and delete Group 4 to N (if defined).
> And if the file has 2 groups, then rename Group 1 and Group 2, disabled Group 3, and delete Groups 4 to N (if any)

2021-09-09 20:07 UTC, Saidmurod1996 commented
Regarding 
> Tests are running successfully, but I think that the test only covers "Edit manually" function and doesn't cover "Import" function

In the above "Edit manually" also shouldn't work, you probably checked that with not less than 3 groups. I've also added above cases to unit test so re run tests just in case.

2021-09-10 14:08 UTC, tim-kodirov commented
LGTM

2021-09-13 19:33 UTC, jfmdev requested changes

2021-09-13 19:33 UTC, jfmdev commented on tests/unit/configFile.spec.js
> +      await ConfigFile.parseJSONFile(
Just one more change: please separate unit tests for each one of these edge cases (e.g. new groups > current groups; new groups < current groups; new groups < 3; new groups = current groups), and group them all using another describe.

Something like:

```js
describe("parseJSONFile()", () => {
    describe("Groups names should be updated is forced (no matter flag's value)", () => {
         it("Groups names should be updated") // newGroups.length == currentGroups.length

         it("New groups should be added") // newGroups.length > currentGroups.length

         it("Old obsolete groups should be removed") // newGroups.length < currentGroups.length

         it("Undefined groups should be disabled") // newGroups.length < 3

```

2021-09-17 00:07 UTC, merged