pix-650-issue-#142 - move options to svelte component
AdvancedThreatAnalytics/threat-analytics-search pull request #152
Opened 2022-01-21 23:18 UTC by Saidmurod1996

pix-650 #142 

To be merged after PR #149

2022-01-27 13:31 UTC, jfmdev requested changes

2022-01-27 13:31 UTC, jfmdev commented on src/components/options/main.svelte
> +}
Now that everything is on Svelte, you don't need to use plain Javascript code to show/hide the tabs, you can use instead `{#if}...{/if}` blocks

2022-01-27 13:31 UTC, jfmdev commented on src/components/options/providers/main.svelte
> +  chrome.runtime.sendMessage({ action: "updateContextualMenu" });
I just noticed that now we have **two** `mainConfigurationUpdated` functions: one in `options/main.svelte` and another in `options/providers/main.svelte`, which is redundant.

Here you should just emit an event so the function from `options/main.svelte` is executed (i.e. here you do `dispatch("updateMainConfiguration")` and on the parent component you do `<Providers bind:this="{providersTab}" initData="{initData}" on:updateMainConfiguration="{mainConfigurationUpdated}" />`

2022-02-02 17:12 UTC, tim-kodirov commented
I am receiving errors when I try to import or edit manually settings on Settings tab, though I can successfully do it in develop branch

2022-02-08 10:12 UTC, jfmdev approved these changes

2022-02-09 14:08 UTC, merged