Issue PIX-829 - Add validation to configuration file options
AdvancedThreatAnalytics/threat-analytics-search pull request #163
Opened 2022-02-14 14:08 UTC by tim-kodirov

Fixes PIX-829

2022-02-14 21:34 UTC, Saidmurod1996 commented
LGTM

2022-02-15 14:11 UTC, tim-kodirov commented
Applied the same logic for showing errors as in previous PRs

2022-02-15 22:10 UTC, jfmdev requested changes
Good work, but the business of having both `value` and `currentValue` to check is error must be shown or not is a bit _hacky_.

Please, instead of that, let's keep a single `value` variable as before, and use something like a `lastError` variable or a `lazy` flag on the validation function (like done on [context menu items](https://github.com/AdvancedThreatAnalytics/threat-analytics-search/pull/159#pullrequestreview-883552939)) to check if the error should be show or not.

2022-02-16 21:08 UTC, jfmdev approved these changes

2022-02-16 21:09 UTC, merged