Feature #59 - Add e2e tests
AdvancedThreatAnalytics/threat-analytics-search pull request #61
Opened 2021-07-07 09:45 UTC by tim-kodirov

Fixes #59 

See [this](https://github.com/AdvancedThreatAnalytics/threat-analytics-search/issues/59#issuecomment-875457650) comment. 

Run e2e test using the command `yarn run test:e2e`

2021-07-08 12:44 UTC, Saidmurod1996 commented
Test sometimes passes, sometimes fails:
![image](https://user-images.githubusercontent.com/30831054/124923652-1880e400-e014-11eb-8929-6bcd8d6af3ab.png)
![image](https://user-images.githubusercontent.com/30831054/124923678-20408880-e014-11eb-812b-de661075fc27.png)

2021-07-08 14:49 UTC, jfmdev requested changes
Also, I think `yarn run lint:fix` wasn't run before committing, **and** commands `yarn run lint` and `yarn run lint:fix` should be updated to also execute over the `test` folder (currently they only parse files on the `src` folder).

2021-07-09 16:48 UTC, Saidmurod1996 commented
All tests are passed now. LGTM

2021-07-12 17:10 UTC, jfmdev approved these changes

2021-07-13 14:02 UTC, merged