Feature/58 add unit testing
AdvancedThreatAnalytics/threat-analytics-search pull request #62
Opened 2021-07-07 23:15 UTC by Saidmurod1996

Fixes #58

2021-07-08 14:27 UTC, jfmdev commented
Since `background.js` file was modified, QA should also include checking that the installation's listener is executed as before.

2021-07-08 14:46 UTC, jfmdev requested changes
Good work, my only comment: `yarn run lint` and `yarn run lint:fix` should also run over files on the `test` folder (currently they only run on the `src` folder).

2021-07-08 17:52 UTC, jfmdev approved these changes

2021-07-09 10:50 UTC, tim-kodirov commented
LGTM. Tests are running successfully

2021-07-12 17:08 UTC, merged