Enhancement/65 migration e2e test
AdvancedThreatAnalytics/threat-analytics-search pull request #71
Opened 2021-07-13 11:59 UTC by tim-kodirov

Fixes #65 

To be merged after https://github.com/AdvancedThreatAnalytics/threat-analytics-search/pull/61

2021-07-13 14:15 UTC, jfmdev requested changes

2021-07-13 14:15 UTC, jfmdev commented on tests/e2e/migration.spec.js
> +    };
I should have been more clear on the issue, but here you are just checking that `_configUrl` is being migrated, and you should check that **all** values (used on v4) are migrated (e.g. `_configLastRefresh`, `_configUseGroups`, `_configEnc`, `_configAutoRefresh`, `_group1Name`, `_allsearch`, `_RSAConfig`, `_RSAallquery`, and so on)

2021-07-13 14:15 UTC, jfmdev commented on tests/e2e/migration.spec.js
> +    );
Besides verifying that `SETTINGS` and `SEARCH_PROVIDERS` have been populated, you should also check `CARBON_BLACK`, `NET_WITNESS` and `RSA_SECURITY`,

2021-07-13 14:21 UTC, jfmdev commented on tests/e2e/migration.spec.js
> +  });
Also `Verify than values don't defined in local store (like mergeSearchProviders which was added on v5) are defined.`

2021-07-14 18:23 UTC, jfmdev reviewed
I'm getting errors when running the tests:

![image](https://user-images.githubusercontent.com/8558447/125672924-b3dd3fa3-0332-4f0b-91df-f3c0a652bf60.png)

2021-07-15 16:46 UTC, Saidmurod1996 commented
I've tested multiple times. Now all tests pass

2021-07-15 16:58 UTC, tim-kodirov commented
Tests are running successfully, but warning messages are shown there:

![image](https://user-images.githubusercontent.com/29039752/125827484-ef3dbc6d-12b0-4ebd-a15d-0d66f031e35a.png)

2021-07-15 19:07 UTC, jfmdev approved these changes

2021-07-15 19:07 UTC, merged