Enhancement/64 test generate json file
AdvancedThreatAnalytics/threat-analytics-search pull request #74
Opened 2021-07-15 19:09 UTC by Saidmurod1996

Fixes #64

2021-07-16 11:30 UTC, tim-kodirov commented
Tests are running successfully

2021-07-16 20:42 UTC, jfmdev requested changes

2021-07-16 20:42 UTC, jfmdev commented on tests/unit/configFile.spec.js
> +const generateJSONFile = jest.spyOn(ConfigFile.default, "generateJSONFile");
No need to add an spy to `generateJSONFile` if the spy-related methods will never be called

2021-07-16 20:42 UTC, jfmdev commented on tests/unit/configFile.spec.js
> +      const result = await generateJSONFile();
If spy-related methods won't be used, here you can just use `ConfigFile.default.parseJSONFile` and `ConfigFile.default.generateJSONFile`

2021-07-16 20:42 UTC, jfmdev commented on tests/unit/configFile.spec.js
> +      await LocalStore.setOne(StoreKey.SETTINGS, settings);
Please change more things... 

* Change two or three values from settings.
* Change the name of one group.
* Remove a search provider, add a new search provider and modify the name of an existing search provider.
* Change a special provider (modify two values from Config and on Queries remove a value and update an existing one).

2021-07-16 20:42 UTC, jfmdev commented on tests/unit/configFile.spec.js
> +      const result = await generateJSONFile();
Same as above: you can just use `ConfigFile.default.parseJSONFile` and `ConfigFile.default.generateJSONFile`

2021-07-19 18:33 UTC, jfmdev approved these changes

2021-07-19 18:35 UTC, merged