Issue #81 - fix open welcome page
AdvancedThreatAnalytics/threat-analytics-search pull request #83
Opened 2021-07-29 11:55 UTC by Saidmurod1996

Fixes #81 

I couldn't reproduce the case Vasu told. Just made it open welcome page only installed for the first time

2021-08-11 21:28 UTC, jfmdev requested changes
The welcome screen is still being opened if the user upgrades from any version outside 4, like from 3.0 to 5.0 or from 5.0 to 5.1 (note the migration script is only run when upgrading from version `4.*`).

2021-08-11 21:28 UTC, jfmdev commented on src/js/migration.js
> -  window.open(MiscURLs.INSTALLED_URL, "_self");
Beside don't opening the welcome screen you should close the current tab (otherwise the tab will show the "migrating" message indefinitely).

2021-08-13 21:25 UTC, jfmdev approved these changes

2021-08-16 17:19 UTC, tim-kodirov commented
LGTM. The welcome screen is not being opened when version is changed

2021-08-17 22:29 UTC, merged